# Kiosk round 2 attack (2026-10-10): the verifier's own mutants, in the builder's spec format (File, Find, Replace).
@(
    @{ Id = "VM01"; Why = "main loop: the due check is commented out (the text is still there)"; Steps = @(@{ File = "agent"; Find = '        try { [void](Invoke-CancelEndIfDue -NowUtc ((Get-Date).ToUniversalTime())) } catch { }'; Replace = '        # try { [void](Invoke-CancelEndIfDue -NowUtc ((Get-Date).ToUniversalTime())) } catch { }' }) }
    @{ Id = "VM02"; Why = "main loop: the due check sits under a false condition"; Steps = @(@{ File = "agent"; Find = '        try { [void](Invoke-CancelEndIfDue -NowUtc ((Get-Date).ToUniversalTime())) } catch { }'; Replace = '        if ($false) { try { [void](Invoke-CancelEndIfDue -NowUtc ((Get-Date).ToUniversalTime())) } catch { } }' }) }
    @{ Id = "VM04"; Why = "the cancel End does not close the launcher"; Steps = @(@{ File = "agent"; Find = '([ordered]@{ mode = "End"; baySessionId = $sid; reason = "BookingCanceled" })'; Replace = '([ordered]@{ mode = "End"; baySessionId = $sid; reason = "BookingCanceled"; closeLauncher = $false })' }) }
    @{ Id = "VM05"; Why = "the cancel End names the wall's session, not the recorded one"; Steps = @(@{ File = "agent"; Find = "        `$sid = [string](Get-KioskProp `$r `"baySessionId`" `"`")`r`n        `$payload = ConvertTo-Json -Compress"; Replace = "        `$sid = [string](Get-PropValue (Read-SessionModelFromDisk) `"baySessionId`" `"`")`r`n        `$payload = ConvertTo-Json -Compress" }) }
    @{ Id = "VM09"; Why = "the stamp says nobody plays on a PREP or READY wall write"; Steps = @(@{ File = "agent"; Find = '            running      = ($null -ne $r)' ; Replace = '            running      = ($null -ne $r -and [string]$st -cnotin @("PREP", "READY"))'; Occurrence = 1 }) }
    @{ Id = "VM19"; Why = "two empty session ids match (an unbound Reset names an unnamed running session)"; Steps = @(@{ File = "agent"; Find = 'if ($x.Length -eq 0 -or $y.Length -eq 0) { return $false }'; Replace = 'if ($x.Length -eq 0 -and $y.Length -eq 0) { return $true }; if ($x.Length -eq 0 -or $y.Length -eq 0) { return $false }' }) }
)
